os: 
  - Visual Studio 2015

platform:
  - Win32
  - Win64

before_build:
  - ps: Invoke-Expression (Invoke-Webrequest 'https://raw.githubusercontent.com/tboox/xmake/master/scripts/get.ps1' -UseBasicParsing).Content
  - cmd: xmake --version

build_script:
  - cmd: if %platform%==Win32 xmake f -c --coroutine=y
  - cmd: if %platform%==Win64 xmake f -c --coroutine=y -a x64
  - cmd: xmake 

test_script:
  - cmd: xmake r demo coroutine_semaphore
